name: eqsphotography
favicon: null
layout_spectrum: 0.8942534057423472
typography_spectrum: 0.27426020544953644
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9052967126481235
  lightness: 0.430642013438046
  saturation: 0.5718814176507294
  rhythmicContrast: 0.9146820025052875
purpose: []
